### ISSUE TITLE
命令"rm-js-comment"导致错误

### ISSUE THREAD

**Issue by catcian** [zhangrenyang/rm-js-comment#1]
([BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
```
babel.transformSync(code, { filename: 'file.ts', presets: [/* your preset */] });
```
See https://babeljs.io/docs/en/options#filename for more information.)

**Comment by zhangrenyang** [comment]
I have fixed this issue, please update [your version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.rm-js-comment)
